#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnMon.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="web")]
	public partial class WebTNDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCauHoi(CauHoi instance);
    partial void UpdateCauHoi(CauHoi instance);
    partial void DeleteCauHoi(CauHoi instance);
    partial void InsertThongTin(ThongTin instance);
    partial void UpdateThongTin(ThongTin instance);
    partial void DeleteThongTin(ThongTin instance);
    partial void InsertCTSuaDe(CTSuaDe instance);
    partial void UpdateCTSuaDe(CTSuaDe instance);
    partial void DeleteCTSuaDe(CTSuaDe instance);
    partial void InsertDeThi(DeThi instance);
    partial void UpdateDeThi(DeThi instance);
    partial void DeleteDeThi(DeThi instance);
    partial void InsertPhanThi(PhanThi instance);
    partial void UpdatePhanThi(PhanThi instance);
    partial void DeletePhanThi(PhanThi instance);
    partial void InsertSuaDe(SuaDe instance);
    partial void UpdateSuaDe(SuaDe instance);
    partial void DeleteSuaDe(SuaDe instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    #endregion
		
		public WebTNDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["webConnectionString2"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public WebTNDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WebTNDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WebTNDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WebTNDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CauHoi> CauHois
		{
			get
			{
				return this.GetTable<CauHoi>();
			}
		}
		
		public System.Data.Linq.Table<ThongTin> ThongTins
		{
			get
			{
				return this.GetTable<ThongTin>();
			}
		}
		
		public System.Data.Linq.Table<CTSuaDe> CTSuaDes
		{
			get
			{
				return this.GetTable<CTSuaDe>();
			}
		}
		
		public System.Data.Linq.Table<DeThi> DeThis
		{
			get
			{
				return this.GetTable<DeThi>();
			}
		}
		
		public System.Data.Linq.Table<PhanThi> PhanThis
		{
			get
			{
				return this.GetTable<PhanThi>();
			}
		}
		
		public System.Data.Linq.Table<SuaDe> SuaDes
		{
			get
			{
				return this.GetTable<SuaDe>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CauHoi")]
	public partial class CauHoi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaCauHoi;
		
		private string _NoiDungCauHoi;
		
		private string _A;
		
		private string _B;
		
		private string _C;
		
		private string _D;
		
		private System.Nullable<int> _DapAnDung;
		
		private EntitySet<DeThi> _DeThis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCauHoiChanging(int value);
    partial void OnMaCauHoiChanged();
    partial void OnNoiDungCauHoiChanging(string value);
    partial void OnNoiDungCauHoiChanged();
    partial void OnAChanging(string value);
    partial void OnAChanged();
    partial void OnBChanging(string value);
    partial void OnBChanged();
    partial void OnCChanging(string value);
    partial void OnCChanged();
    partial void OnDChanging(string value);
    partial void OnDChanged();
    partial void OnDapAnDungChanging(System.Nullable<int> value);
    partial void OnDapAnDungChanged();
    #endregion
		
		public CauHoi()
		{
			this._DeThis = new EntitySet<DeThi>(new Action<DeThi>(this.attach_DeThis), new Action<DeThi>(this.detach_DeThis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCauHoi", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaCauHoi
		{
			get
			{
				return this._MaCauHoi;
			}
			set
			{
				if ((this._MaCauHoi != value))
				{
					this.OnMaCauHoiChanging(value);
					this.SendPropertyChanging();
					this._MaCauHoi = value;
					this.SendPropertyChanged("MaCauHoi");
					this.OnMaCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungCauHoi", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string NoiDungCauHoi
		{
			get
			{
				return this._NoiDungCauHoi;
			}
			set
			{
				if ((this._NoiDungCauHoi != value))
				{
					this.OnNoiDungCauHoiChanging(value);
					this.SendPropertyChanging();
					this._NoiDungCauHoi = value;
					this.SendPropertyChanged("NoiDungCauHoi");
					this.OnNoiDungCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A", DbType="NVarChar(600)")]
		public string A
		{
			get
			{
				return this._A;
			}
			set
			{
				if ((this._A != value))
				{
					this.OnAChanging(value);
					this.SendPropertyChanging();
					this._A = value;
					this.SendPropertyChanged("A");
					this.OnAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B", DbType="NVarChar(600)")]
		public string B
		{
			get
			{
				return this._B;
			}
			set
			{
				if ((this._B != value))
				{
					this.OnBChanging(value);
					this.SendPropertyChanging();
					this._B = value;
					this.SendPropertyChanged("B");
					this.OnBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C", DbType="NVarChar(600)")]
		public string C
		{
			get
			{
				return this._C;
			}
			set
			{
				if ((this._C != value))
				{
					this.OnCChanging(value);
					this.SendPropertyChanging();
					this._C = value;
					this.SendPropertyChanged("C");
					this.OnCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D", DbType="NVarChar(600)")]
		public string D
		{
			get
			{
				return this._D;
			}
			set
			{
				if ((this._D != value))
				{
					this.OnDChanging(value);
					this.SendPropertyChanging();
					this._D = value;
					this.SendPropertyChanged("D");
					this.OnDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DapAnDung", DbType="Int")]
		public System.Nullable<int> DapAnDung
		{
			get
			{
				return this._DapAnDung;
			}
			set
			{
				if ((this._DapAnDung != value))
				{
					this.OnDapAnDungChanging(value);
					this.SendPropertyChanging();
					this._DapAnDung = value;
					this.SendPropertyChanged("DapAnDung");
					this.OnDapAnDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CauHoi_DeThi", Storage="_DeThis", ThisKey="MaCauHoi", OtherKey="MaCauHoi")]
		public EntitySet<DeThi> DeThis
		{
			get
			{
				return this._DeThis;
			}
			set
			{
				this._DeThis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DeThis(DeThi entity)
		{
			this.SendPropertyChanging();
			entity.CauHoi = this;
		}
		
		private void detach_DeThis(DeThi entity)
		{
			this.SendPropertyChanging();
			entity.CauHoi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThongTin")]
	public partial class ThongTin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTTCN;
		
		private System.Nullable<int> _MaTK;
		
		private string _HoTen;
		
		private string _GioiThieu;
		
		private string _DiaChi;
		
		private string _DienThoai;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _AnhCaNhan;
		
		private EntitySet<SuaDe> _SuaDes;
		
		private EntityRef<TaiKhoan> _TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTTCNChanging(int value);
    partial void OnMaTTCNChanged();
    partial void OnMaTKChanging(System.Nullable<int> value);
    partial void OnMaTKChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnGioiThieuChanging(string value);
    partial void OnGioiThieuChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnAnhCaNhanChanging(string value);
    partial void OnAnhCaNhanChanged();
    #endregion
		
		public ThongTin()
		{
			this._SuaDes = new EntitySet<SuaDe>(new Action<SuaDe>(this.attach_SuaDes), new Action<SuaDe>(this.detach_SuaDes));
			this._TaiKhoan = default(EntityRef<TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTTCN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaTTCN
		{
			get
			{
				return this._MaTTCN;
			}
			set
			{
				if ((this._MaTTCN != value))
				{
					this.OnMaTTCNChanging(value);
					this.SendPropertyChanging();
					this._MaTTCN = value;
					this.SendPropertyChanged("MaTTCN");
					this.OnMaTTCNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTK", DbType="Int")]
		public System.Nullable<int> MaTK
		{
			get
			{
				return this._MaTK;
			}
			set
			{
				if ((this._MaTK != value))
				{
					if (this._TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTKChanging(value);
					this.SendPropertyChanging();
					this._MaTK = value;
					this.SendPropertyChanged("MaTK");
					this.OnMaTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(150)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiThieu", DbType="NVarChar(300)")]
		public string GioiThieu
		{
			get
			{
				return this._GioiThieu;
			}
			set
			{
				if ((this._GioiThieu != value))
				{
					this.OnGioiThieuChanging(value);
					this.SendPropertyChanging();
					this._GioiThieu = value;
					this.SendPropertyChanged("GioiThieu");
					this.OnGioiThieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(150)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="NVarChar(10)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhCaNhan", DbType="VarChar(50)")]
		public string AnhCaNhan
		{
			get
			{
				return this._AnhCaNhan;
			}
			set
			{
				if ((this._AnhCaNhan != value))
				{
					this.OnAnhCaNhanChanging(value);
					this.SendPropertyChanging();
					this._AnhCaNhan = value;
					this.SendPropertyChanged("AnhCaNhan");
					this.OnAnhCaNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThongTin_SuaDe", Storage="_SuaDes", ThisKey="MaTTCN", OtherKey="MaTTCN")]
		public EntitySet<SuaDe> SuaDes
		{
			get
			{
				return this._SuaDes;
			}
			set
			{
				this._SuaDes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_ThongTin", Storage="_TaiKhoan", ThisKey="MaTK", OtherKey="MaTK", IsForeignKey=true)]
		public TaiKhoan TaiKhoan
		{
			get
			{
				return this._TaiKhoan.Entity;
			}
			set
			{
				TaiKhoan previousValue = this._TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoan.Entity = null;
						previousValue.ThongTins.Remove(this);
					}
					this._TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.ThongTins.Add(this);
						this._MaTK = value.MaTK;
					}
					else
					{
						this._MaTK = default(Nullable<int>);
					}
					this.SendPropertyChanged("TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SuaDes(SuaDe entity)
		{
			this.SendPropertyChanging();
			entity.ThongTin = this;
		}
		
		private void detach_SuaDes(SuaDe entity)
		{
			this.SendPropertyChanging();
			entity.ThongTin = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTSuaDe")]
	public partial class CTSuaDe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaSuaDe;
		
		private int _MaDe;
		
		private System.Nullable<System.DateTime> _NgaySua;
		
		private EntityRef<DeThi> _DeThi;
		
		private EntityRef<SuaDe> _SuaDe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSuaDeChanging(int value);
    partial void OnMaSuaDeChanged();
    partial void OnMaDeChanging(int value);
    partial void OnMaDeChanged();
    partial void OnNgaySuaChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySuaChanged();
    #endregion
		
		public CTSuaDe()
		{
			this._DeThi = default(EntityRef<DeThi>);
			this._SuaDe = default(EntityRef<SuaDe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSuaDe", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaSuaDe
		{
			get
			{
				return this._MaSuaDe;
			}
			set
			{
				if ((this._MaSuaDe != value))
				{
					if (this._SuaDe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSuaDeChanging(value);
					this.SendPropertyChanging();
					this._MaSuaDe = value;
					this.SendPropertyChanged("MaSuaDe");
					this.OnMaSuaDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDe", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaDe
		{
			get
			{
				return this._MaDe;
			}
			set
			{
				if ((this._MaDe != value))
				{
					if (this._DeThi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDeChanging(value);
					this.SendPropertyChanging();
					this._MaDe = value;
					this.SendPropertyChanged("MaDe");
					this.OnMaDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySua", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySua
		{
			get
			{
				return this._NgaySua;
			}
			set
			{
				if ((this._NgaySua != value))
				{
					this.OnNgaySuaChanging(value);
					this.SendPropertyChanging();
					this._NgaySua = value;
					this.SendPropertyChanged("NgaySua");
					this.OnNgaySuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DeThi_CTSuaDe", Storage="_DeThi", ThisKey="MaDe", OtherKey="MaDe", IsForeignKey=true)]
		public DeThi DeThi
		{
			get
			{
				return this._DeThi.Entity;
			}
			set
			{
				DeThi previousValue = this._DeThi.Entity;
				if (((previousValue != value) 
							|| (this._DeThi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DeThi.Entity = null;
						previousValue.CTSuaDes.Remove(this);
					}
					this._DeThi.Entity = value;
					if ((value != null))
					{
						value.CTSuaDes.Add(this);
						this._MaDe = value.MaDe;
					}
					else
					{
						this._MaDe = default(int);
					}
					this.SendPropertyChanged("DeThi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SuaDe_CTSuaDe", Storage="_SuaDe", ThisKey="MaSuaDe", OtherKey="MaSuaDe", IsForeignKey=true)]
		public SuaDe SuaDe
		{
			get
			{
				return this._SuaDe.Entity;
			}
			set
			{
				SuaDe previousValue = this._SuaDe.Entity;
				if (((previousValue != value) 
							|| (this._SuaDe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SuaDe.Entity = null;
						previousValue.CTSuaDes.Remove(this);
					}
					this._SuaDe.Entity = value;
					if ((value != null))
					{
						value.CTSuaDes.Add(this);
						this._MaSuaDe = value.MaSuaDe;
					}
					else
					{
						this._MaSuaDe = default(int);
					}
					this.SendPropertyChanged("SuaDe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DeThi")]
	public partial class DeThi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDe;
		
		private string _TenDe;
		
		private string _AnhBia;
		
		private System.Nullable<System.DateTime> _NgaycapNhat;
		
		private System.Nullable<int> _MaPhan;
		
		private System.Nullable<int> _MaCauHoi;
		
		private EntitySet<CTSuaDe> _CTSuaDes;
		
		private EntityRef<CauHoi> _CauHoi;
		
		private EntityRef<PhanThi> _PhanThi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDeChanging(int value);
    partial void OnMaDeChanged();
    partial void OnTenDeChanging(string value);
    partial void OnTenDeChanged();
    partial void OnAnhBiaChanging(string value);
    partial void OnAnhBiaChanged();
    partial void OnNgaycapNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaycapNhatChanged();
    partial void OnMaPhanChanging(System.Nullable<int> value);
    partial void OnMaPhanChanged();
    partial void OnMaCauHoiChanging(System.Nullable<int> value);
    partial void OnMaCauHoiChanged();
    #endregion
		
		public DeThi()
		{
			this._CTSuaDes = new EntitySet<CTSuaDe>(new Action<CTSuaDe>(this.attach_CTSuaDes), new Action<CTSuaDe>(this.detach_CTSuaDes));
			this._CauHoi = default(EntityRef<CauHoi>);
			this._PhanThi = default(EntityRef<PhanThi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDe
		{
			get
			{
				return this._MaDe;
			}
			set
			{
				if ((this._MaDe != value))
				{
					this.OnMaDeChanging(value);
					this.SendPropertyChanging();
					this._MaDe = value;
					this.SendPropertyChanged("MaDe");
					this.OnMaDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDe", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string TenDe
		{
			get
			{
				return this._TenDe;
			}
			set
			{
				if ((this._TenDe != value))
				{
					this.OnTenDeChanging(value);
					this.SendPropertyChanging();
					this._TenDe = value;
					this.SendPropertyChanged("TenDe");
					this.OnTenDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhBia", DbType="VarChar(50)")]
		public string AnhBia
		{
			get
			{
				return this._AnhBia;
			}
			set
			{
				if ((this._AnhBia != value))
				{
					this.OnAnhBiaChanging(value);
					this.SendPropertyChanging();
					this._AnhBia = value;
					this.SendPropertyChanged("AnhBia");
					this.OnAnhBiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaycapNhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaycapNhat
		{
			get
			{
				return this._NgaycapNhat;
			}
			set
			{
				if ((this._NgaycapNhat != value))
				{
					this.OnNgaycapNhatChanging(value);
					this.SendPropertyChanging();
					this._NgaycapNhat = value;
					this.SendPropertyChanged("NgaycapNhat");
					this.OnNgaycapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhan", DbType="Int")]
		public System.Nullable<int> MaPhan
		{
			get
			{
				return this._MaPhan;
			}
			set
			{
				if ((this._MaPhan != value))
				{
					if (this._PhanThi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhanChanging(value);
					this.SendPropertyChanging();
					this._MaPhan = value;
					this.SendPropertyChanged("MaPhan");
					this.OnMaPhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCauHoi", DbType="Int")]
		public System.Nullable<int> MaCauHoi
		{
			get
			{
				return this._MaCauHoi;
			}
			set
			{
				if ((this._MaCauHoi != value))
				{
					if (this._CauHoi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCauHoiChanging(value);
					this.SendPropertyChanging();
					this._MaCauHoi = value;
					this.SendPropertyChanged("MaCauHoi");
					this.OnMaCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DeThi_CTSuaDe", Storage="_CTSuaDes", ThisKey="MaDe", OtherKey="MaDe")]
		public EntitySet<CTSuaDe> CTSuaDes
		{
			get
			{
				return this._CTSuaDes;
			}
			set
			{
				this._CTSuaDes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CauHoi_DeThi", Storage="_CauHoi", ThisKey="MaCauHoi", OtherKey="MaCauHoi", IsForeignKey=true)]
		public CauHoi CauHoi
		{
			get
			{
				return this._CauHoi.Entity;
			}
			set
			{
				CauHoi previousValue = this._CauHoi.Entity;
				if (((previousValue != value) 
							|| (this._CauHoi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CauHoi.Entity = null;
						previousValue.DeThis.Remove(this);
					}
					this._CauHoi.Entity = value;
					if ((value != null))
					{
						value.DeThis.Add(this);
						this._MaCauHoi = value.MaCauHoi;
					}
					else
					{
						this._MaCauHoi = default(Nullable<int>);
					}
					this.SendPropertyChanged("CauHoi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhanThi_DeThi", Storage="_PhanThi", ThisKey="MaPhan", OtherKey="MaPhan", IsForeignKey=true)]
		public PhanThi PhanThi
		{
			get
			{
				return this._PhanThi.Entity;
			}
			set
			{
				PhanThi previousValue = this._PhanThi.Entity;
				if (((previousValue != value) 
							|| (this._PhanThi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhanThi.Entity = null;
						previousValue.DeThis.Remove(this);
					}
					this._PhanThi.Entity = value;
					if ((value != null))
					{
						value.DeThis.Add(this);
						this._MaPhan = value.MaPhan;
					}
					else
					{
						this._MaPhan = default(Nullable<int>);
					}
					this.SendPropertyChanged("PhanThi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTSuaDes(CTSuaDe entity)
		{
			this.SendPropertyChanging();
			entity.DeThi = this;
		}
		
		private void detach_CTSuaDes(CTSuaDe entity)
		{
			this.SendPropertyChanging();
			entity.DeThi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhanThi")]
	public partial class PhanThi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPhan;
		
		private string _TenPhan;
		
		private EntitySet<DeThi> _DeThis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhanChanging(int value);
    partial void OnMaPhanChanged();
    partial void OnTenPhanChanging(string value);
    partial void OnTenPhanChanged();
    #endregion
		
		public PhanThi()
		{
			this._DeThis = new EntitySet<DeThi>(new Action<DeThi>(this.attach_DeThis), new Action<DeThi>(this.detach_DeThis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaPhan
		{
			get
			{
				return this._MaPhan;
			}
			set
			{
				if ((this._MaPhan != value))
				{
					this.OnMaPhanChanging(value);
					this.SendPropertyChanging();
					this._MaPhan = value;
					this.SendPropertyChanged("MaPhan");
					this.OnMaPhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhan", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string TenPhan
		{
			get
			{
				return this._TenPhan;
			}
			set
			{
				if ((this._TenPhan != value))
				{
					this.OnTenPhanChanging(value);
					this.SendPropertyChanging();
					this._TenPhan = value;
					this.SendPropertyChanged("TenPhan");
					this.OnTenPhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhanThi_DeThi", Storage="_DeThis", ThisKey="MaPhan", OtherKey="MaPhan")]
		public EntitySet<DeThi> DeThis
		{
			get
			{
				return this._DeThis;
			}
			set
			{
				this._DeThis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DeThis(DeThi entity)
		{
			this.SendPropertyChanging();
			entity.PhanThi = this;
		}
		
		private void detach_DeThis(DeThi entity)
		{
			this.SendPropertyChanging();
			entity.PhanThi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SuaDe")]
	public partial class SuaDe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaSuaDe;
		
		private System.Nullable<int> _MaTTCN;
		
		private string _NguoiSua;
		
		private EntitySet<CTSuaDe> _CTSuaDes;
		
		private EntityRef<ThongTin> _ThongTin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSuaDeChanging(int value);
    partial void OnMaSuaDeChanged();
    partial void OnMaTTCNChanging(System.Nullable<int> value);
    partial void OnMaTTCNChanged();
    partial void OnNguoiSuaChanging(string value);
    partial void OnNguoiSuaChanged();
    #endregion
		
		public SuaDe()
		{
			this._CTSuaDes = new EntitySet<CTSuaDe>(new Action<CTSuaDe>(this.attach_CTSuaDes), new Action<CTSuaDe>(this.detach_CTSuaDes));
			this._ThongTin = default(EntityRef<ThongTin>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSuaDe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaSuaDe
		{
			get
			{
				return this._MaSuaDe;
			}
			set
			{
				if ((this._MaSuaDe != value))
				{
					this.OnMaSuaDeChanging(value);
					this.SendPropertyChanging();
					this._MaSuaDe = value;
					this.SendPropertyChanged("MaSuaDe");
					this.OnMaSuaDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTTCN", DbType="Int")]
		public System.Nullable<int> MaTTCN
		{
			get
			{
				return this._MaTTCN;
			}
			set
			{
				if ((this._MaTTCN != value))
				{
					if (this._ThongTin.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTTCNChanging(value);
					this.SendPropertyChanging();
					this._MaTTCN = value;
					this.SendPropertyChanged("MaTTCN");
					this.OnMaTTCNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiSua", DbType="NVarChar(150)")]
		public string NguoiSua
		{
			get
			{
				return this._NguoiSua;
			}
			set
			{
				if ((this._NguoiSua != value))
				{
					this.OnNguoiSuaChanging(value);
					this.SendPropertyChanging();
					this._NguoiSua = value;
					this.SendPropertyChanged("NguoiSua");
					this.OnNguoiSuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SuaDe_CTSuaDe", Storage="_CTSuaDes", ThisKey="MaSuaDe", OtherKey="MaSuaDe")]
		public EntitySet<CTSuaDe> CTSuaDes
		{
			get
			{
				return this._CTSuaDes;
			}
			set
			{
				this._CTSuaDes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThongTin_SuaDe", Storage="_ThongTin", ThisKey="MaTTCN", OtherKey="MaTTCN", IsForeignKey=true)]
		public ThongTin ThongTin
		{
			get
			{
				return this._ThongTin.Entity;
			}
			set
			{
				ThongTin previousValue = this._ThongTin.Entity;
				if (((previousValue != value) 
							|| (this._ThongTin.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThongTin.Entity = null;
						previousValue.SuaDes.Remove(this);
					}
					this._ThongTin.Entity = value;
					if ((value != null))
					{
						value.SuaDes.Add(this);
						this._MaTTCN = value.MaTTCN;
					}
					else
					{
						this._MaTTCN = default(Nullable<int>);
					}
					this.SendPropertyChanged("ThongTin");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTSuaDes(CTSuaDe entity)
		{
			this.SendPropertyChanging();
			entity.SuaDe = this;
		}
		
		private void detach_CTSuaDes(CTSuaDe entity)
		{
			this.SendPropertyChanging();
			entity.SuaDe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTK;
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private string _Email;
		
		private EntitySet<ThongTin> _ThongTins;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTKChanging(int value);
    partial void OnMaTKChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public TaiKhoan()
		{
			this._ThongTins = new EntitySet<ThongTin>(new Action<ThongTin>(this.attach_ThongTins), new Action<ThongTin>(this.detach_ThongTins));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaTK
		{
			get
			{
				return this._MaTK;
			}
			set
			{
				if ((this._MaTK != value))
				{
					this.OnMaTKChanging(value);
					this.SendPropertyChanging();
					this._MaTK = value;
					this.SendPropertyChanged("MaTK");
					this.OnMaTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="VarChar(50)")]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_ThongTin", Storage="_ThongTins", ThisKey="MaTK", OtherKey="MaTK")]
		public EntitySet<ThongTin> ThongTins
		{
			get
			{
				return this._ThongTins;
			}
			set
			{
				this._ThongTins.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ThongTins(ThongTin entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = this;
		}
		
		private void detach_ThongTins(ThongTin entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = null;
		}
	}
}
#pragma warning restore 1591
